FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY .air.toml ./

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
