"use client";
import React from "react";

export default function MainFooter() {
    return (
        <footer className="w-full py-8 mt-auto bg-white border-t border-slate-100 relative z-[5]">
            <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4 text-center md:text-left">
                <div className="space-y-1">
                    <p className="text-xs text-slate-400 font-bold tracking-wider uppercase">
                        Non-Profit Organization
                    </p>
                    <p className="text-sm text-slate-500">
                        © {new Date().getFullYear()} Moesekai. Generated by <span className="font-bold">Moesekai Dev Team</span>.
                    </p>
                </div>

                <div className="text-xs text-slate-400 max-w-md leading-relaxed">
                    <p>
                        本站仅提供素材展示，游戏版权归 <span className="font-bold">SEGA / Colorful Palette</span> 所有。
                    </p>
                    <p>
                        这是一个粉丝向的网站，一个仅用于研究目的的同人数据库。
                    </p>
                </div>
            </div>
        </footer>
    );
}
